dz_1 ready
ArtemKrotenok/KrotenokAndroid pull request #1
Opened 2020-08-15 12:44 UTC by ArtemKrotenok

The first version of homework 1 is ready.

2020-08-15 14:35 UTC, tim-teacher commented on AndroidBeginner/app/build.gradle
> +    buildToolsVersion "30.0.1"
buildToolsVersion либо лучше не указывать либо она должна совпадать с compileSdkVersion
например 29.0.2

2020-08-15 14:35 UTC, tim-teacher commented on AndroidBeginner/app/build.gradle
> +    implementation fileTree(dir: "libs", include: ["*.jar"])
эту строку можно удалить, либы мы будем только ссылками подключать.

2020-08-15 14:39 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/TextExchangeActivity.java
> +                CharSequence contentTextView1 = textView1.getText();
давай все содержимое вынесем в метод, а то как то многовато кода в onCreate(), да и выглядит все сплошным текстом как то.

2020-08-17 19:28 UTC, ArtemKrotenok commented on AndroidBeginner/app/build.gradle
> +    buildToolsVersion "30.0.1"
fixed

2020-08-17 19:29 UTC, ArtemKrotenok commented on AndroidBeginner/app/build.gradle
> +    implementation fileTree(dir: "libs", include: ["*.jar"])
fixed

2020-08-17 19:32 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/TextExchangeActivity.java
> +                CharSequence contentTextView1 = textView1.getText();
fixed

2020-08-19 14:54 UTC, tim-teacher requested changes

2020-08-19 14:54 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/TextExchangeActivity.java
> +                CharSequence contentTextView1 = textView1.getText();
содержимое public void onClick(View v) { 
нужно вынести

2020-08-24 13:42 UTC, tim-teacher approved these changes

2020-08-30 09:14 UTC, merged