dz_15 redy
ArtemKrotenok/KrotenokAndroid pull request #12
Opened 2020-11-28 18:51 UTC by ArtemKrotenok

Home work #15 - Student app is redy

[app-debug.zip](https://github.com/ArtemKrotenok/KrotenokAndroid/files/5611077/app-debug.zip)

![Screenshot_1606588196](https://user-images.githubusercontent.com/58876771/100523733-d19c5780-31c3-11eb-85fd-f8c9c65fd198.png)
![Screenshot_1606588218](https://user-images.githubusercontent.com/58876771/100523736-d234ee00-31c3-11eb-8fc6-bb4e1139a153.png)
![Screenshot_1606588226](https://user-images.githubusercontent.com/58876771/100523737-d234ee00-31c3-11eb-9b8b-5a5f2b382384.png)
![Screenshot_1606588240](https://user-images.githubusercontent.com/58876771/100523738-d2cd8480-31c3-11eb-996f-cee30414ded4.png)

2020-11-29 00:57 UTC, tim-teacher requested changes

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    private static final String TEXT_MESSAGE_STUDENT_DELETE = "Student was deleted";
в string.xml

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        studentId = Long.parseLong(arguments.get(StudentListActivity.STUDENT_ID).toString());
думаю тут проще заменить на  intent.getLongExtra() вместо приведения типов и рисков нарваться на исключение.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    private void handleButtonEditStudentOnClick() {
не критично, но желательно не делать таких длинных названий методов, если есть возможность. Тут можно вполне сократить до "onEdit(), onDelete() и тд.".

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        intent.putExtra(StudentListActivity.STUDENT_ID, studentId);
Не нужно переисользовать на всех экранах оду и туже переменную. Экраны должны быть независимыми по максимум.

Во вторых, переменная для putExtra должна находится в том активити в который ты передаешь данные. Тоесть в данном случае она должна быть в StudentDetailsActivity, а не в StudentListActivity.

Тоже самое для остальных экранов.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        finish();
хм, а разве finish(); не достаточно? Ведь ты же попадешь на предыдущий экран, тоесть на StudentListActivity, поэтому нет смысла его открыть через интент. Мы должны идти по стеку экранов, и возвращаться также по нему. Иначе ты вечно уходишь вперед по стеку и у тебя копиться огромная история, да и в этом случае у тебя каждый раз будет новый объект для StudentListActivity создаваться.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +    private static final String TEXT_MESSAGE_STUDENT_ADD = "New student add";
все это перенести в string.xml.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +        studentRepository = StudentRepository.getInstance();
я бы в самом верху написал:
private StudentRepository studentRepository = StudentRepository.getInstance();
что бы исключить риски NullPointerException если вдруг кто обратиться к репозиторию до вызова метода "initVerbals()".

И для остальных экранов тоже так.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +        if (studentId != 0l) {
тоже самое, выше чуть описал где лучше создавать константу "STUDENT_ID".

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +            finish();
Тоже самое, попробуй просто выйти по стеку активиттей назад, используя только финиш, этого должно хватить.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +    private void updateStudentInBD(long studentId) {
rename to updateStudent. Активити не дожно знать или управлять тем где мы будем сохранять данные, может через какоето время мы будет на сервере сохранять и тогда название будет неверное.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +        studentBD.setAge(Integer.parseInt(editTextAge.getText().toString()));
всю эту логику давай в репозиторий в метод studentRepository.update(studentBD); перенесем. Активти - это работа с пользователем, тут бизнес логики и логики обновления быть не должно.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +        newStudent.setAge(Integer.parseInt(editTextAge.getText().toString()));
тоже самое.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +            return false;
Нужно создать класс Utils и там сделать статик метод с проверкой на url. Вдруг еще где нужа будет.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentItemDecoration.java
> +    public static final int MARGIN_TOP_ITEM = 50;
хм, это же все в пискселах а значит может все поехать на разных экранах. Нужно задавать в дп и конвертировать в пикселы, тогда будет одинаково на всех девайсах.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +    private List<Student> studentList;
этот лист у тебя в репозитории храниться, тут он не нужен.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +        adapter.notifyDataSetChanged();
хм, тут что то странное с логикой обновления, во первых в двух местах initVerbals() и      protected void onResume(), во сторых как то непонятно все это в адаптер закидывается. Нужно будет обсудить тут подробнее на созвоне.

2020-11-29 00:57 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +                intent.putExtra(STUDENT_ID, "0");
"0" вынести в константу наверх.

2020-12-05 10:47 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    private static final String TEXT_MESSAGE_STUDENT_DELETE = "Student was deleted";
fixed

2020-12-05 12:20 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        studentId = Long.parseLong(arguments.get(StudentListActivity.STUDENT_ID).toString());
fixed

2020-12-05 12:22 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    private void handleButtonEditStudentOnClick() {
fixed

2020-12-05 12:39 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        intent.putExtra(StudentListActivity.STUDENT_ID, studentId);
fixed

2020-12-05 12:45 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        finish();
fixed

2020-12-05 12:45 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +    private static final String TEXT_MESSAGE_STUDENT_ADD = "New student add";
fixed

2020-12-05 12:50 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +        studentRepository = StudentRepository.getInstance();
fixed

2020-12-05 12:54 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +        if (studentId != 0l) {
fixed

2020-12-05 13:07 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +            finish();
fixed

2020-12-05 13:14 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +    private void updateStudentInBD(long studentId) {
fixed

2020-12-05 13:34 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentEditActivity.java
> +            return false;
fixed

2020-12-05 14:01 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentItemDecoration.java
> +    public static final int MARGIN_TOP_ITEM = 50;
fixed

2020-12-05 14:05 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +    private List<Student> studentList;
fixed

2020-12-05 14:05 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +        adapter.notifyDataSetChanged();
fixed

2020-12-05 14:07 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +                intent.putExtra(STUDENT_ID, "0");
fixed

2020-12-08 21:37 UTC, tim-teacher approved these changes
Пару моментов только подправь перед мерджингом.

2020-12-08 21:37 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        Student student = studentRepository.findById(studentId);
А если вернет null? :)

2020-12-08 21:37 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +        adapter.notifyDataSetChanged();
adapter.notifyDataSetChanged(); нужно внутри метода          adapter.addAll(studentRepository.getAllSortByName());  вызывать, а тут нужно удалить его.

2020-12-12 17:25 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        Student student = studentRepository.findById(studentId);
fixed

2020-12-12 17:25 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +        adapter.notifyDataSetChanged();
fixed

2020-12-12 17:28 UTC, merged