dz_18 ready
ArtemKrotenok/KrotenokAndroid pull request #15
Opened 2020-12-27 15:26 UTC by ArtemKrotenok

dz_18 ready

2020-12-27 22:28 UTC, tim-teacher requested changes
На созвоне я еще качну твой код и открою в студии и пройдемся еще дополнительно по нему, кроме этих замечаний нужно еще глянуть вместе визуально.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        fragmentTransaction.commit();
Лучше вот так:
`long studentId = getIntent().getLongExtra(StudentDetailsFragment.DETAILS_STUDENT_ID, StudentDetailsFragment.DEFAULT_VALUE_STUDENT_ID);
setValue();
initListeners();

if(savedInstanceState == null) {
    SupportFragmentManager fragmentmanager = getSupportFragmentManager().beginTransaction();
    FragmentTransaction fragmentTransaction = fragmentmanager.beginTransaction();
    StudentDetailsFragment studentDetailsFragment =  StudentDetailsFragment.newInstance(studentId);
     fragmentTransaction.replace(R.id.fragment_student_details_placeholder, studentDetailsFragment);
     fragmentTransaction.commit();`
     
Тоесть:
1) Немного разделяем часть кода связанную с фрагментами и остальгую (чисто визуально и порядок написания, а то у тебя все вперемешку).
2) if(savedInstanceState == null) нужна для предотвращения случая, когда твое приложени было в бекграунде и андроид его удалил из памяти. В этом случае если юзер откроет это приложения из недавних(квадратная кнопка как правило), то андроид попытается восстановить приложение в том же виде как было, и сам добавит фрагмент который был в активити. В этом случае savedInstanceState не нулевой. Если проверку не сделать то ты добавишь фрагмент дважды. А в товем случае с методом add онибы лежали один поверх другого.
3) Лушче использовать метод replace, а не add. Add нужен немного для других случаев, да и с replace меньше проблем если, что-то не то накодишь.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +    private Context context;
Никаких контекстов, ты же и так внутри контекста.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +        context = container.getContext();
Это строчку брать.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +        selectedListener = (OnSelectedListener) context;
Это нужно делать в методе onActivityCreated.
Типа такого:
onActivityCreated() {
    if(getActivity() instenceOf OnSelectedListener) {
        selectedListener = (OnSelectedListener) getActivity();
    } 
}

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +        studentListFragment = new StudentListFragment();
Тут тоже самое насчет savedInstanceState.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +    public void update() {
@Override методы лучше вверху активитей и фрагментов распологать.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +        selectedListener = (OnSelectedListener) context;
Тоже самое как выше писал.

2020-12-27 22:28 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +        context = container.getContext();
Тоже самое.

2021-01-03 13:04 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +        fragmentTransaction.commit();
fixed

2021-01-03 13:04 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +    private Context context;
fixed

2021-01-03 13:04 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +        context = container.getContext();
fixed

2021-01-03 13:04 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +        selectedListener = (OnSelectedListener) context;
fixed

2021-01-03 13:05 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListActivity.java
> +        studentListFragment = new StudentListFragment();
fixed

2021-01-03 13:05 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +    public void update() {
fixed

2021-01-03 13:05 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +        selectedListener = (OnSelectedListener) context;
fixed

2021-01-03 13:05 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +        context = container.getContext();
fixed

2021-01-06 15:53 UTC, tim-teacher requested changes
Немного по мелочи осталось.

2021-01-06 15:53 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    public static final String DETAILS_STUDENT_ID = "DETAILS_STUDENT_ID";
Можно на private поменять.

2021-01-06 15:53 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    public static void start(Context context, long studentId) {
Такие методы в самый верх классу лечше закидывать, к тому же это статит, статики тоже обычно повыше закидываются. Исключение только если приватный метод.

2021-01-06 15:53 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +    public static final long DEFAULT_VALUE_STUDENT_ID = 0L;
Можно поменять в private.

2021-01-06 15:53 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +        Intent intent = new Intent(getActivity(), StudentEditActivity.class);
А чего эту частьне вынесли также как остальные в статик метод start?

2021-01-06 15:53 UTC, tim-teacher commented on StudentApp/app/src/main/res/layout-land/activity_student_list.xml
> +    <ScrollView
Норм решение, но лучше делать скрол внутри конкретного фрагмента, что бы фрагмент мог сам все контролировать.

2021-01-10 08:43 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    public static void start(Context context, long studentId) {
fixed

2021-01-10 08:56 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +        Intent intent = new Intent(getActivity(), StudentEditActivity.class);
fixed

2021-01-10 09:19 UTC, ArtemKrotenok commented on StudentApp/app/src/main/res/layout-land/activity_student_list.xml
> +    <ScrollView
fixed

2021-01-16 12:44 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsActivity.java
> +    public static final String DETAILS_STUDENT_ID = "DETAILS_STUDENT_ID";
fixed

2021-01-16 12:45 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentDetailsFragment.java
> +    public static final long DEFAULT_VALUE_STUDENT_ID = 0L;
fixed

2021-01-18 20:10 UTC, tim-teacher approved these changes

2021-01-24 10:13 UTC, merged