Coronavirus app is ready
ArtemKrotenok/KrotenokAndroid pull request #18
Opened 2021-02-07 10:57 UTC by ArtemKrotenok

Coronavirus application first version is ready.
Additionally, the following features are implemented:
1) On the map, points of foci of infection with coronavirus (there may be several points in the country)
2) According to the points of the foci of infection, a list of countries with common infected is formed, then the resulting list is sorted
3) Added a button to refresh data in the menu

![Screenshot_1612694847](https://user-images.githubusercontent.com/58876771/107144477-723d8f00-694c-11eb-8698-472a4b7071d1.png)
![Screenshot_1612694856](https://user-images.githubusercontent.com/58876771/107144479-72d62580-694c-11eb-98d5-6978fc2efb79.png)

2021-02-07 15:34 UTC, tim-teacher requested changes

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/build.gradle
> +        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
remove

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataLoader.java
> +                    e.printStackTrace();
Нужно как то обрабатывать ошибки, убедиться что с этим все ок.

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataLoader.java
> +                    callback.onResult(readStream);
con.disconnect()

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
remove, если не используется

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataParsingUtil.java
> +            coronaVirusData.setLastCheckTimeText(rootJSONObject.getString("lastCheckTimeText"));
теги вынести в константы

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataParsingUtil.java
> +            countryData.setName(jsonObject.getString("country"));
тоже самое

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataParsingUtil.java
> +            public int compare(InfectionCountry infectionCountry1, InfectionCountry infectionCountry2) {
Сохранять в коллекцию число как есть, а разбивать на разряды только в активити или адаптере ресайкла уже в момент отображения.

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/repository/InfectionPointEntity.java
> +    public void setNavLat(double navLat) {
nav можо убрать

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    private MapFragment mapFragment;
private ViewUpdate  infoPage;
    private ViewUpdate mapPage;
    
    interface ViewUpdate{
       updateData();
    }

2021-02-07 15:34 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
savedInstanceState нужно проверить на null, что бы не добавлять фрагменты дважды.

2021-02-07 15:34 UTC, tim-teacher commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +        recyclerView.addItemDecoration(itemDecoration);
Вернуть строчку в предыдущее месте, что бы файлы не было в git.

2021-02-21 08:28 UTC, ArtemKrotenok commented on CoronavirusApp/app/build.gradle
> +        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
fixed

2021-02-21 08:43 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataLoader.java
> +                    e.printStackTrace();
fixed

2021-02-21 08:43 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataLoader.java
> +                    callback.onResult(readStream);
fixed

2021-02-21 09:07 UTC, ArtemKrotenok commented on CoronavirusApp/app/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
fixed

2021-02-21 11:19 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataParsingUtil.java
> +            coronaVirusData.setLastCheckTimeText(rootJSONObject.getString("lastCheckTimeText"));
fixed

2021-02-21 11:19 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataParsingUtil.java
> +            countryData.setName(jsonObject.getString("country"));
fixed

2021-02-21 11:30 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/net/DataParsingUtil.java
> +            public int compare(InfectionCountry infectionCountry1, InfectionCountry infectionCountry2) {
fixed

2021-02-21 11:32 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/repository/InfectionPointEntity.java
> +    public void setNavLat(double navLat) {
fixed

2021-02-21 12:28 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    private MapFragment mapFragment;
fixed

2021-02-21 12:34 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
fixed

2021-02-21 12:40 UTC, ArtemKrotenok commented on StudentApp/app/src/main/java/com/gmail/artemkrot/StudentListFragment.java
> +        recyclerView.addItemDecoration(itemDecoration);
fixed

2021-02-21 18:42 UTC, tim-teacher requested changes

2021-02-21 18:42 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    private void startInfoFragment() {
MapFragment mapFragment = new MapFragment();
mapPage = mapFragment;

2021-02-21 18:42 UTC, tim-teacher commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    private void startMapFragment() {
и тоже самое тут.

2021-02-28 09:57 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    private void startInfoFragment() {
fixed

2021-02-28 09:57 UTC, ArtemKrotenok commented on CoronavirusApp/app/src/main/java/com/gmail/artemkrot/coronavirus/ui/MainActivity.java
> +    private void startMapFragment() {
fixed

2021-02-28 10:13 UTC, merged