Dz 2
ArtemKrotenok/KrotenokAndroid pull request #2
Opened 2020-08-22 12:22 UTC by ArtemKrotenok

Dz #2 ready

2020-08-24 13:46 UTC, tim-teacher requested changes

2020-08-24 13:46 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/MainMenuActivity.java
> +    private void initListenerButtonSelectTextExchangeActivity() {
в данной задаче немного выгоднее сделать один лисенер для всех кнопок а внутри лисенера сделать что то такое:

val intent = when(view.id) {
   R.id.button_menu_text_exchange_activity -> {
      Intent(MainMenuActivity.this, TextExchangeActivity.class)
  }
   R.id. button_menu_flags_activity -> {
        Intent(MainMenuActivity.this, FlagsActivity.class)
   }
}

и затем вызвать:
 startActivity(intent);

так будет значительно меньше кода.

2020-08-24 13:46 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/TextExchangeActivity.java
> +public class TextExchangeActivity extends Activity {
А что делает эта задача в данном пул реквесте? Делать ветку нужно всегда от мастера а не от другого ДЗ.

2020-08-30 10:04 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/TextExchangeActivity.java
> +public class TextExchangeActivity extends Activity {
Take into consideration)

2020-08-30 10:04 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/MainMenuActivity.java
> +    private void initListenerButtonSelectTextExchangeActivity() {
fixed

2020-08-30 10:32 UTC, merged