dz_3 ready
ArtemKrotenok/KrotenokAndroid pull request #3
Opened 2020-08-30 14:34 UTC by ArtemKrotenok

2020-09-01 19:50 UTC, tim-teacher requested changes

2020-09-01 19:50 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_flags.xml
> +            <TextView
А зачем использовать TextView ради закраски фона? Ну тоесть TextView создан для вывода текста и если эта функция не используется значит мы зря инициализируем такой объект. Тут можно использовать более простые элементы, такие как FrameLayout или даже View

2020-09-01 19:50 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_flags.xml
> +        <LinearLayout
Этот LinearLayout можно оптимизировать убрав один из дочерних элементов, в данном случает это TextView.
Сматри, тебе нужно 3 цвета. Что если родительскому layout задать фон @color/color_flag_red" а внутри него положить только два TextView с первыми двумя цветами? Тоесть последнего как бы не будет но из за того, что там будет виден фон родительского LinearLayout будет выглядеть все также.
Единсвенное в LinearLayout нужно задать свойство weightSum = 3, тоесть два TextView займут по 1 и еще один останется свободный. Без этого свойства внутреннние элементы просто растянуться.

2020-09-06 12:16 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_flags.xml
> +            <TextView
fixed

2020-09-06 12:16 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_flags.xml
> +        <LinearLayout
fixed

2020-09-07 18:28 UTC, tim-teacher requested changes

2020-09-07 18:28 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_flags.xml
> +            <FrameLayout
тут тоже давай также как и выше оптимизируем и уберем лишний элемент, ну и дальше тоже самое если такие случаи есть.

2020-09-13 13:42 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_flags.xml
> +            <FrameLayout
fixed

2020-09-15 19:47 UTC, tim-teacher approved these changes

2020-09-27 08:34 UTC, merged