dz_4 ready
ArtemKrotenok/KrotenokAndroid pull request #4
Opened 2020-09-06 13:37 UTC by ArtemKrotenok

dz_4 ready 

![Screenshot_1599399228](https://user-images.githubusercontent.com/58876771/92327010-392c8600-f05f-11ea-8693-58bd57312e3f.png)
![Screenshot_1599399250](https://user-images.githubusercontent.com/58876771/92327012-39c51c80-f05f-11ea-8acb-1824c799e376.png)

2020-09-07 18:35 UTC, tim-teacher requested changes

2020-09-07 18:35 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_login_linear.xml
> +    android:background="@drawable/background"
фон будет деформироваться в зависимости от разрешения экрана, и если там есть картинки мелкие то они будут либо в высоту либо в ширину вытянуты. А такого не должно быть.

Нужно использовать комбинацию FrameLayout и ImageView. ImageView в нем задаешь фон и закидываешь его внутрь FrameLayout(root элемент). После чего ImageView должно быть растянута на весь экран но если гдето не удается ровно то края должно обрезаться, для этого есть параметр внутри ImageView.

Далее внутри FrameLayout уже идет весь контент. На созвоне еще подробнее поясню.

2020-09-07 18:35 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_login_linear.xml
> +            android:background="#50ffffff"
все цвета вынести в value/color.xml

2020-09-07 18:35 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_login_linear.xml
> +            android:layout_marginTop="10dp"
все размеры вынести в value/dimen.xml

2020-09-07 18:35 UTC, tim-teacher commented on AndroidBeginner/app/src/main/res/layout/activity_main_menu.xml
> +            android:text="LoginLinearActivity"
все стринги вынести в value/strings.xml

2020-09-13 15:08 UTC, ArtemKrotenok commented
![Screenshot_1600006298](https://user-images.githubusercontent.com/58876771/93021581-10bb0380-f5ec-11ea-85e8-1000fc8314e5.png)
![Screenshot_1600006332](https://user-images.githubusercontent.com/58876771/93021584-11ec3080-f5ec-11ea-93e7-dce91bbccce5.png)

2020-09-13 15:08 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_main_menu.xml
> +            android:text="LoginLinearActivity"
fixed

2020-09-13 15:11 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_login_linear.xml
> +            android:layout_marginTop="10dp"
fixed

2020-09-13 15:11 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_login_linear.xml
> +            android:background="#50ffffff"
fixed

2020-09-13 15:11 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/res/layout/activity_login_linear.xml
> +    android:background="@drawable/background"
fixed

2020-09-15 19:54 UTC, tim-teacher approved these changes

2020-09-27 08:40 UTC, merged