dz_7 ready
ArtemKrotenok/KrotenokAndroid pull request #5
Opened 2020-09-15 19:39 UTC by ArtemKrotenok

2020-09-15 19:57 UTC, tim-teacher requested changes

2020-09-15 19:57 UTC, tim-teacher commented on AndroidBeginner/app/build.gradle
> +    implementation 'jp.wasabeef:picasso-transformations:2.2.1'
хм, вообще это достаточно легко сделать вручную написав свой класс трансформации картинки для пикассо, но да ладно ).

2020-09-15 19:57 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/ImageActivity.java
> +        View.OnClickListener onClickListener = new View.OnClickListener() {
очень длинный и жутко выглядищий лисенер, нужно разбить на более мелкие метолы ну или хотя бы содержимое onClick вынести в отдельный метод.

2020-09-27 14:06 UTC, ArtemKrotenok commented on AndroidBeginner/app/build.gradle
> +    implementation 'jp.wasabeef:picasso-transformations:2.2.1'
fixed

2020-09-27 14:06 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/ImageActivity.java
> +        View.OnClickListener onClickListener = new View.OnClickListener() {
fixed

2020-09-27 20:31 UTC, tim-teacher approved these changes

2020-10-04 08:48 UTC, merged