dz_11 ready
ArtemKrotenok/KrotenokAndroid pull request #7
Opened 2020-10-18 16:15 UTC by ArtemKrotenok

2020-10-18 16:16 UTC, ArtemKrotenok commented
![Screenshot_1603037077](https://user-images.githubusercontent.com/58876771/96373609-5ed89f00-1176-11eb-9a62-7ca699a3f79d.png)
![Screenshot_1603037093](https://user-images.githubusercontent.com/58876771/96373612-6009cc00-1176-11eb-88a8-3cbacdbeac8b.png)
![Screenshot_1603037269](https://user-images.githubusercontent.com/58876771/96373615-6009cc00-1176-11eb-84cd-2ef9081534f0.png)

2020-10-18 16:17 UTC, ArtemKrotenok commented
[app-debug.zip](https://github.com/ArtemKrotenok/KrotenokAndroid/files/5397800/app-debug.zip)

2020-10-19 11:55 UTC, tim-teacher requested changes

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +    public static final int FULL_ARC = 360;
думаю можно все эти статик переменные сделать private

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        textPaint.setColor(OUT_TEXT_COLOR);
еще желательно вызвать rectPaint.setAntiAlias(true) и так для каждого Paint, что бы сглаживать линии.

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        resultPercentList = new ArrayList<>();
лучше сразу написать:
private List<Integer> resultPercentLis = new ArrayList<>();
тоже самое и для RectF и Paint.

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        oval = new RectF();
oval переименуй в ovalRectF

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +            this.inputDataList = new ArrayList<>();
тоже самое можно инициализировать вверху сразу когда переменную создаешь.

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        oval.set(0, 0, getMeasuredHeight(), getMeasuredWidth());
это нужно делать в методе onSizeChanged(). onDraw() метод вызывается очень часто, поэтому не нужно тут делать какие либо действия не связанные с рисованием.

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        resultPercentList = getResultPercentList(inputDataList);
getResultPercentList() - хорошо бы эти расчеты делать один раз, когда поменялись данные, а не при каждом вызове onDraw().

2020-10-19 11:55 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        int desiredWidth = DESIRED_WIDTH;
это нужно убрать, View должна быть тех размеров которые мы задаем в xml, либо если там задали match parent, то должна занимать максимально возможное пространство.

2020-10-25 12:35 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +    public static final int FULL_ARC = 360;
fixed

2020-10-25 12:36 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        textPaint.setColor(OUT_TEXT_COLOR);
fixed

2020-10-25 12:36 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        resultPercentList = new ArrayList<>();
fixed

2020-10-25 12:37 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        oval = new RectF();
fixed

2020-10-25 12:37 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +            this.inputDataList = new ArrayList<>();
fixed

2020-10-25 12:38 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        oval.set(0, 0, getMeasuredHeight(), getMeasuredWidth());
fixed

2020-10-25 12:40 UTC, ArtemKrotenok commented on AndroidBeginner/app/src/main/java/com/gmail/krotenok/PieChartView.java
> +        resultPercentList = getResultPercentList(inputDataList);
fixed

2020-10-25 13:34 UTC, ArtemKrotenok commented
[app-debug2.zip](https://github.com/ArtemKrotenok/KrotenokAndroid/files/5434814/app-debug2.zip)

2020-10-26 11:28 UTC, tim-teacher approved these changes

2020-11-08 10:01 UTC, merged